name: Deploy React App to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci

      - name: Build React app
        run: |
          npm run build
        env:
          CI: false

      - name: Verify build directory
        run: |
          if [ ! -d "./build" ]; then
            echo "ERROR: build directory not found. npm run build likely failed."
            ls -la
            exit 1
          fi

      - name: Archive artifact
        run: |
          tar -czf build.tar.gz build
        # if you want to keep an artifact in Actions UI too:
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build
